### ISSUE TITLE
no line numbers when open lvim with "nvim filename"

### ISSUE THREAD

**Issue by luxus** [lvim-tech/lvim#10]
when I open a file directly I don't see line numbers. 
when I open nvim and open a file in there I have line numbers.
is this intended?

**Comment by lvim-tech** [comment]
Which branch do you use?
OS?
Try to update to the latest neovim version.

**Comment by luxus** [comment]
branch master
os Macos 
I actually had to reinstall with brew install neovim (the install was some weeks old)
problem is fixed.. 
I'm really impressed by your work! 
and thanks for helping with my stupid problems :D
