### ISSUE TITLE
list zsh as a requirement ( and maybe rsync )

### ISSUE THREAD

**Issue by Sebastiaan76** [lvim-tech/lvim#11]
I didn't have zsh on my system, and this doesn't install without it. The settings file also defaults to ZSH, so probably best to call it out explicitly as a dependency?

i also had to install rsync for one of the plugins to work.

Other than that, very slick!

**Comment by lvim-tech** [comment]
I removed shell (zsh) from the global settings.
Yes, rsync is required - for [vim-arsync](https://github.com/kenn7/vim-arsync).
The Readme file has been updated.
Thanks!
