### ISSUE TITLE
Search function not working - vim-clap disabled

### ISSUE THREAD

**Issue by Sebastiaan76** [lvim-tech/lvim#12]
Search function on dashboard is trying to call :Clap files, but causes an error. 

I noticed all the stuff in configs to do with vim-clap has been commented out. Might want to update the dashboard Search to something else in that case?

**Comment by lvim-tech** [comment]
Oh, I removed Clap. I left only Snap. Dashboard fixed in last commit.
Many thanks, @Sebastiaan76
