### ISSUE TITLE
Cannot enter lvim after git

### ISSUE THREAD

**Issue by jicvi** [lvim-tech/lvim#14]

**Comment by lvim-tech** [comment]
Please, post error message.

**Comment by jicvi** [comment]
@lvim-tech 
No error！
I installed lvim in the docker ubuntu container

**Comment by lvim-tech** [comment]
Neovim version?

**Comment by jicvi** [comment]
> Neovim version?

jclivi@6dac0c16f9c4:/$ nvim --version
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by jicvi** [comment]
![11111111111111120210821045642](https://user-images.githubusercontent.com/14210650/130316667-75bab71e-4648-473b-bfd5-26da49c50321.png)
![22222222_20210821045733](https://user-images.githubusercontent.com/14210650/130316672-e6fbcde3-1478-4b49-9fc2-f0b876ea66b2.png)

**Comment by lvim-tech** [comment]
LVIM support Neovim 0.5+

**Comment by jicvi** [comment]
> LVIM support Neovim 0.5+

Thank you, I will try the updated version

**Comment by jicvi** [comment]
Docker failed to install Lvim:

Error detected while processing /root/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim.lua:97: module 'vim.uri' not found:
        no field package.preload['vim.uri']
        no file './vim/uri.lua'
        no file '/work-path/config/nvim-config/neovim-nightly/.deps/usr/share/luajit-2.1.0-beta3/vim/uri.lua'
        no file '/usr/local/share/lua/5.1/vim/uri.lua'
        no file '/usr/local/share/lua/5.1/vim/uri/init.lua'
        no file '/work-path/config/nvim-config/neovim-nightly/.deps/usr/share/lua/5.1/vim/uri.lua'
        no file '/work-path/config/nvim-config/neovim-nightly/.deps/usr/share/lua/5.1/vim/uri/init.lua'
        no file './vim/uri.so'
        no file '/usr/local/lib/lua/5.1/vim/uri.so'
        no file '/work-path/config/nvim-config/neovim-nightly/.deps/usr/lib/lua/5.1/vim/uri.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './vim.so'
        no file '/usr/local/lib/lua/5.1/vim.so'
        no file '/work-path/config/nvim-config/neovim-nightly/.deps/usr/lib/lua/5.1/vim.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
Press ENTER or type command to continue

**Comment by jicvi** [comment]
@lvim-tech 
Docker failed to install Lvim:

Error detected while processing /root/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim.lua:97: module 'vim.uri' not found:
no field package.preload['vim.uri']
no file './vim/uri.lua'
no file '/work-path/config/nvim-config/neovim-nightly/.deps/usr/share/luajit-2.1.0-beta3/vim/uri.lua'
no file '/usr/local/share/lua/5.1/vim/uri.lua'
no file '/usr/local/share/lua/5.1/vim/uri/init.lua'
no file '/work-path/config/nvim-config/neovim-nightly/.deps/usr/share/lua/5.1/vim/uri.lua'
no file '/work-path/config/nvim-config/neovim-nightly/.deps/usr/share/lua/5.1/vim/uri/init.lua'
no file './vim/uri.so'
no file '/usr/local/lib/lua/5.1/vim/uri.so'
no file '/work-path/config/nvim-config/neovim-nightly/.deps/usr/lib/lua/5.1/vim/uri.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file './vim.so'
no file '/usr/local/lib/lua/5.1/vim.so'
no file '/work-path/config/nvim-config/neovim-nightly/.deps/usr/lib/lua/5.1/vim.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
Press ENTER or type command to continue

**Comment by lvim-tech** [comment]
The problem is the path in your docker containet. This is not a LVIM configuration problem.
