### ISSUE TITLE
Leader Key + Vertical Highlight bar column 80

### ISSUE THREAD

**Issue by vmarlier** [lvim-tech/lvim#15]
Hello,

1. Is it possible to define a leader key, to be used inside the KeyMaps file ?
For exemple I would like to :NvimTreeToggle as a combination of ", + ;" instead of "S+x".

2. Is it also possible to remove the "Highlight column on the column 80", I've searched inside the configurations but I cannot see where it from.. ?

3. Also, I've noticed that I cannot copy paste with the basic shortcut Ctrl+c/v, instead it seems it's the yank functionnalty of vim that is being used, is there a way to modify this behaviour ? 

Thank You

**Comment by lvim-tech** [comment]
Add this:

```
local configs = {}
local funcs = require "core.funcs"

configs["options"] = function()
    local custom_opt = {
        colorcolumn = ""
    }
    funcs.options_set(custom_opt)
    local custom_keymaps = {
        {"<YourKey-YourKey>", ":NvimTreeToggle<CR>"}
    }
    funcs.keymaps("n", {noremap = false, silent = true}, custom_keymaps)
end

return configs
```

to `lvim/lua/configs/custom/init.lua`

", + ;" - not working, use C-Key, S-Key or A-Key

For Ctrl+c/v - change config your terminal

**Comment by lvim-tech** [comment]
If you want rewrite leader keys:

1. Add this:

```
local modules = {}

local tools_config = require("modules.custom.configs.tools")

modules["AckslD/nvim-whichkey-setup.lua"] = {
    event = {"VimEnter", "BufReadPre"},
    requires = "liuchengxu/vim-which-key",
    config = tools_config.whichkey
}

return modules
```

to `lvim/lua/modules/custom/init.lua`

2. Create file `lvim/lua/modules/custom/tools/init.lua`

3. Add your config (for example use `lvim/lua/modules/global/tools/init.lua`)

**Comment by lvim-tech** [comment]
Did that help you?

**Comment by vmarlier** [comment]
Yes thank you
