### ISSUE TITLE
Why no hint

### ISSUE THREAD

**Issue by DemoorBug** [lvim-tech/lvim#16]
`:LspInstall html`
But still no hint.
What else do I need to configure?
![image](https://user-images.githubusercontent.com/18387615/133888819-0fcc2bae-39bc-4a7e-af74-4972f02ca1e9.png)

**Comment by lvim-tech** [comment]
Update to the last commit. I integrated `vim-vsnip` and `friendly-snippets`
Then run:
`:PackerSync`

Result:
![Screenshot from 2021-09-18 17-50-43](https://user-images.githubusercontent.com/82431193/133893053-62009da6-358b-4781-9a5a-1917e8c024d7.png)

**Comment by DemoorBug** [comment]
@lvim-tech This solves my problem.

**Comment by DemoorBug** [comment]
https://github.com/lvim-tech/lvim#base
I only have nodejs and neovim installed. do I have to install the others?

**Comment by DemoorBug** [comment]
https://github.com/lvim-tech/lvim#configs-settings 
The links here are not working

**Comment by lvim-tech** [comment]
Thanks for the links. Updated.

`do I have to install the others?`
Some plugins require this software.
