### ISSUE TITLE
attempt to concatenate upvalue 'home' (a nil value)

### ISSUE THREAD

**Issue by webmandman** [lvim-tech/lvim#17]
first time running lvim. I just moved my init.vim file out of the install directory and clone this repo there. 

any help would be nice. 

![image](https://user-images.githubusercontent.com/991677/135546899-3808f1f7-3c1e-40fc-8d4d-8786319ae803.png)

**Comment by webmandman** [comment]
ok. so I looked at global.lua and noticed its looking for environment variable called HOME. so I added one. Not sure if I should, its obviously not part of the install instructions. 

anyways, I starteed neovim and immediately got a message about some syntax not being correct, it vanished right away and PACKER installed a ton of plugins.

**Comment by webmandman** [comment]
everytime I start up LVIM it spits out this message 5 times:
the syntax of the command is incorrect. Then the LVIM startup screen appears. 

any help on this would be nice.

**Comment by lvim-tech** [comment]
Are you using WSL?

**Comment by webmandman** [comment]
I do, but not all the time. Windows is my work environment I have to abide by.

**Comment by lvim-tech** [comment]
Just install under WSL.
