### ISSUE TITLE
Space + e (explorer) gives an error 

### ISSUE THREAD

**Issue by kimusan** [lvim-tech/lvim#20]
When trying to open the explorer via space + e I get the following error on a clean install (code as of today):
E492: Not an editor command: NvimTreeToggle  

Seems like it might need some configuration or calling of its setup function, but I am not entirely sure where this should be done

**Comment by kimusan** [comment]
so in 1.0 the Explorer is removed?

**Comment by lvim-tech** [comment]
<S-x> - NvimTree
