### ISSUE TITLE
opining tsx file "Autostart for angularls failed: matching root directory not detected."

### ISSUE THREAD

**Issue by kirilligum** [lvim-tech/lvim#25]
Steps to reproduce

1. install lvim 
`rm -rf ~/.config/nvim
rm -rf ~/.cache/nvim
rm -rf ~/.local/share/nvim
git clone https://github.com/lvim-tech/lvim.git ~/.config/nvim
`
2.  install expo (to generate .tsx)
`npm install --global expo-cli
`
3. create app with expo 
`expo init my-app
cd my-app
`
4. open tsx file 
`
nvim App.tsx
`
error:
```
Autostart for angularls failed: matching root directory not detected.
Autostart for angularls failed: matching root directory not detected.
Press ENTER or type command to continue
```

per https://github.com/neovim/nvim-lspconfig/issues/1359 , I tried `sudo npm install -g typescript` without any result

**Comment by lvim-tech** [comment]
Fixed in v1.1.1
