### ISSUE TITLE
Custom config

### ISSUE THREAD

**Issue by diego-rapoport** [lvim-tech/lvim#27]
Hi guys. Sorry if I'm doing something wrong or if I couldn't understand quite well the wiki, but I tried to customize my dash board using the same code as wiki show and I only got errors.
Already tried to put code inside `local config{}` and outside of it, but none works. Is there an easier way to customize my plugins or could you make the wiki explanation more explicit?
I also couldn't understand the way custom config files are loaded and how they work exactly. Noob here.

**Comment by lvim-tech** [comment]
For plugins

In `lua/modules/custom/init.lua`:

```lua
local ui_config = require("modules.custom.configs.ui")
modules["glepnir/dashboard-nvim"] = {
    event = "VimEnter",
    config = ui_config.dashboard_nvim
}
```

In `lua/modules/custom/init.lua`:

```lua
function config.dashboard_nvim()
-- your code
end
```

**Comment by lvim-tech** [comment]
For configs

In `lua/configs/custom/init.lua`:

```lua
configs["any_name_of_functions"] = function()
-- your code
end
```

**Comment by lvim-tech** [comment]
I will close this question.
If you need more help, open it again.
