### ISSUE TITLE
Tree-sitter note

### ISSUE THREAD

**Issue by Bashe** [lvim-tech/lvim#30]
Hi

Cudos for the nice job!!

However, currently, I can't use it on my work machine (Centos 7) because it tries to install tree-sitter-cli via 'npm'... 

The problem is that node compilation requires 'c99' flag to be set, but it can't since the toolchain is very old... so building the tree-sitter-cli fails.

However, I can avoid this issue by using the Rust version of the tree-sitter-cli (installed via cargo), and that one works flawlessly!

So my suggestion would be to check for tree-sitter-cli installation, BEFORE attempting to install it. Then this setup should work on old systems as well!

FYI: on my home machine (Sway flavor of EndeavourOS) works flawlessly.

Once again - thanks for the very nice project!

**Comment by lvim-tech** [comment]
This problem is related with the plugin [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter), not with lvim configuration.
Many plugins require nvim-treesitter.

**Comment by Bashe** [comment]
Got that, thanks!

However, I'm still missing some understanding of vim/neovim, since I just started to use this editor...

I know that many plugins require the tree-sitter, but I think they are using the application, they do not install it? Typically the user installs it?

Anyway, thanks for the feedback - I guess I'll need to do some RTFM in the tree-sitter... 🤔
