### ISSUE TITLE
Packer autoinstall does not work.

### ISSUE THREAD

**Issue by palandovalex** [lvim-tech/lvim#32]
Fresh install, nvim and after that - lvim. So, .local/nvim is empty. I tried to use PackerSync - it fails with this trace

E5108: Error executing lua /home/username/.config/nvim/lua/core/pack.lua:27: module 'packer' not found:
        no field package.preload['packer']
        no file './packer.lua'
        no file '/usr/share/luajit-2.1.0-beta3/packer.lua'
        no file '/usr/local/share/lua/5.1/packer.lua'
        no file '/usr/local/share/lua/5.1/packer/init.lua'
        no file '/usr/share/lua/5.1/packer.lua'
        no file '/usr/share/lua/5.1/packer/init.lua'
        no file './packer.so'
        no file '/usr/local/lib/lua/5.1/packer.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/packer.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/username/.config/nvim/lua/core/pack.lua:27: in function 'load_packer'
        /home/username/.config/nvim/lua/core/pack.lua:65: in function '__index'
        [string ":lua"]:1: in main chunk

**Comment by palandovalex** [comment]
I lock in pack.lua...
function plugins.ensure_plugins()
never used.

**Comment by palandovalex** [comment]
Tryed to open lua file in nvim - 

Обнаружена ошибка при обработке BufWinEnter Автокоманды для "*":
E5108: Error executing lua ...username/.config/nvim/lua/languages/base/utils/init.lua:1: module 'lspconfig' not found:
        no field package.preload['lspconfig']
        no file './lspconfig.lua'
        no file '/usr/share/luajit-2.1.0-beta3/lspconfig.lua'
        no file '/usr/local/share/lua/5.1/lspconfig.lua'
        no file '/usr/local/share/lua/5.1/lspconfig/init.lua'
        no file '/usr/share/lua/5.1/lspconfig.lua'
        no file '/usr/share/lua/5.1/lspconfig/init.lua'
        no file './lspconfig.so'
        no file '/usr/local/lib/lua/5.1/lspconfig.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/lspconfig.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        ...username/.config/nvim/lua/languages/base/utils/init.lua:1: in main chunk
        [C]: in function 'require'
        ...username/.config/nvim/lua/languages/base/languages/lua.lua:9: in main chunk
        [C]: in function 'dofile'
        /home/username/.config/nvim/lua/languages/base/init.lua:126: in function 'init_language'
        /home/username/.config/nvim/lua/languages/base/init.lua:105: in function 'start_language'
        /home/username/.config/nvim/lua/languages/base/init.lua:77: in function 'setup'

**Comment by lvim-tech** [comment]
Fixed in last commit and v1.7.7
Thanks for report, @palandovalex !
