### ISSUE TITLE
In Packer - endless "luarocks-hererocks: installing hererocks"

### ISSUE THREAD

**Issue by palandovalex** [lvim-tech/lvim#33]
System info:
$nvim -v
NVIM v0.8.0-dev:
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

$ lua -v
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

$ luarocks --version
/usr/bin/luarocks 3.8.0
LuaRocks main command-line interface

$ hererocks -v
Hererocks 0.25.1

**Comment by lvim-tech** [comment]
More info about error? Logfile?

**Comment by palandovalex** [comment]
try to remove hererocks and luarocks.. Error still remains.

What log file? Where it shoul be?

Checkhealth

[checkhealth.txt](https://github.com/lvim-tech/lvim/files/8976557/checkhealth.txt)

**Comment by lvim-tech** [comment]
WARNING: **luarocks**: not available

**Comment by palandovalex** [comment]
I installed luarocks by sudo apt install luarocks
and i installed luacheck by luarocks

And installed hererocks by pip install hererocks
and problem is still here:

I found Info about this issye in packer.nvim repo:
https://github.com/wbthomason/packer.nvim/issues/283

I am not using luaver, or other lua version manager

**Comment by lvim-tech** [comment]
I can't reproduce your problem
My steps:
1. deleted ~/local/nvim/
2. deleted ~/cache/nvim/
3. run nvim
and hererocks is install from Packer

Maybe your problem in lua.

**Comment by lvim-tech** [comment]
Did you find any solution for your problem?

**Comment by aasutossh** [comment]
probably using mac, I have the same issue.
