### ISSUE TITLE
After fust install, try to use insert mode, got exeption:

### ISSUE THREAD

**Issue by palandovalex** [lvim-tech/lvim#34]
Обнаружена ошибка при обработке InsertEnter Автокоманды для "*":                                                                                                 
E5108: Error executing lua ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:48: module 'cmp' not found:
        no field package.preload['cmp']
        no file './cmp.lua'
        no file '/usr/share/luajit-2.1.0-beta3/cmp.lua'
        no file '/usr/local/share/lua/5.1/cmp.lua'
        no file '/usr/local/share/lua/5.1/cmp/init.lua'
        no file '/usr/share/lua/5.1/cmp.lua'
        no file '/usr/share/lua/5.1/cmp/init.lua'
        no file './cmp.so'
        no file '/usr/local/lib/lua/5.1/cmp.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/cmp.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:48: in function '_on_insert_enter'
        [string ":lua"]:1: in main chunk

**Comment by lvim-tech** [comment]
Try :PackerSync

**Comment by palandovalex** [comment]
:PackerSync - all loaded, exept luarocks-hererocks(endless loading)
Error still remains
