### ISSUE TITLE
Crashing luarocks-hererocks

### ISSUE THREAD

**Issue by corasaurus-hex** [lvim-tech/lvim#36]
When running :PackerInstall/Sync the luarocks-hererocks step fails due to a compilation error. It turns out that you must set the `MACOSX_DEPLOYMENT_TARGET` environment variable on macOS now in order for builds to go through for luajit. In my case I'm on macOS 12.4 and so I added `export MACOSX_DEPLOYMENT_TARGET="12.4"` to my `.zshrc`.  It would probably be nice if lvim set this env var or at least output something helpful when it fails to build.

Thanks!

**Comment by corasaurus-hex** [comment]
See this issue https://github.com/LuaJIT/LuaJIT/issues/764

**Comment by lvim-tech** [comment]
I'm not using MacOS.
I can add vim.fn.setenv("MACOSX_DEPLOYMENT_TARGET", "version")
When I run :lua vim.notify(vim.inspect(vim.loop.os_uname())) I  get info
```
{
  machine = "x86_64",
  release = "5.18.2-1-default",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Tue Jun 7 06:08:54 UTC 2022 (695cfee)"
}
```
@corasaurus-hex , can You help me? Run this command and tell me: release == 12.4 (your version)?
Thanks in advance!

**Comment by aasutossh** [comment]
Hello, I have Macbook Air M1, I get
```
{
  machine = "arm64",
  release = "21.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101"
}
```
How to install `lvim`? it's stuck at installing `hererocks`.
My Macos version is 12.5.1.

**Comment by lvim-tech** [comment]
See comment above.

**Comment by lvim-tech** [comment]
See comment above.

**Comment by corasaurus-hex** [comment]
Mine says:

```
{
  machine = "x86_64",
  release = "21.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64"
}
```

**Comment by corasaurus-hex** [comment]
This is relevant on macos:

```
❯ sw_vers -productVersion
12.5.1
```

**Comment by corasaurus-hex** [comment]
and even more on the nose on macos:

```
❯ MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion | awk -F \. {'print $1 "." $2}') echo $MACOSX_DEPLOYMENT_TARGET
12.5
```

**Comment by aasutossh** [comment]
> export MACOSX_DEPLOYMENT_TARGET="12.4"

`export MACOSX_DEPLOYMENT_TARGET="12.5.1"` still doesn't help.

**Comment by lvim-tech** [comment]
@aasutossh , try install neovim from source:
```
git clone https://github.com/neovim/neovim
cd neovim || return
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
```

**Comment by aasutossh** [comment]
building neovim from source doesn't have any effect. it's same as before. stuck at installing hererocks...

**Comment by aasutossh** [comment]
Also, how do you clean (uninstall) neovim after being installed with `sudo make install`?
