### ISSUE TITLE
update buffer after format with new formatter (yapf)

### ISSUE THREAD

**Issue by rolfst** [lvim-tech/lvim#37]
Hi I am trying to integrate yapf as a new formatter for python code. for this I forked [mason.nvim](https://github.com/rolfst/mason.nvim)
however when I do this:

```
language_configs["lsp"] = function()
    languages_setup.setup_languages({
        ["language"] = "diagnostic-languageserver",
        ["dependencies"] = {
            "yapf",
            ...
        },
        ["diagnostic-languageserver"] = { "diagnosticls", diagnosticls_config },
    })
end

```
```
    formatters = {
       ...
        yapf = {
            command = "yapf",
            args = { "--quiet", "-i", "%file" },
        },
    }

```
and change my formatters to:
```
formatters_filetypes = {
 python = yapf,
}
```
the format will get applied after I execute `:LspFormatting`, however the buffer won't update to the new content. but when I do `:e!` the buffer will get updated with the new content. 
When I save the buffer no formatter will get called at all and after doing `:e!` no changes show up at all. 
Any suggestions what I can do to make the new formatter work propperly?

**Comment by lvim-tech** [comment]
Are you install dependencies?
![Screenshot from 2022-08-14 18-55-49](https://user-images.githubusercontent.com/82431193/184545039-3c5f6e13-40bf-4fde-ae57-2cca50069587.png)

**Comment by lvim-tech** [comment]
I try your clone, install yapf and code formatting on save `<C-c>s`
Buffer updated!

**Comment by rolfst** [comment]
[Screencast from 17-08-22 09:01:15.webm](https://user-images.githubusercontent.com/38265/185055816-6134a1ae-88ac-49a7-839e-3c72ba1cd47e.webm)
weird I have to manually update my screen continuously

**Comment by lvim-tech** [comment]
Try:
```
formatters = {
    yapf = {
        command = "yapf",
        args = { "%file" },
    },
}

**Comment by rolfst** [comment]
youre a life saver. now I can give my feature to the main repo ;)

**Comment by rolfst** [comment]
we cheered too soon. with these arguments it does format but it removes all new additions

**Comment by lvim-tech** [comment]
What new additions?

**Comment by rolfst** [comment]
when I add new code to a python file it the formatter removes the new code

**Comment by lvim-tech** [comment]
And now:
```
formatters = {
    yapf = {
        command = "yapf",
        args = { "--quiet" },
    },
}
```

**Comment by rolfst** [comment]
hmm weird, I tried this as well before. but anyway it seems to work now. tnx.
