### ISSUE TITLE
Error since 2.1.30 (2022-09-04) upgrade

### ISSUE THREAD

**Issue by rolfst** [lvim-tech/lvim#39]
When I startup  my nvim since the upgrade I get the following error:
```
Error detected while processing  .config/nvim/init.lua:                                                                                                                                                                             
Not exist command for filetypes or format invalid, if use json please execute :CRFiletype or if use lua edit setup
```
it doesn't matter if I start nvim with just nvim or if I start nvim with a file I want to open.

I have not made any changes to my init.lua itself.
I get this issue also when I do a new git clone of lvim

**Comment by lvim-tech** [comment]
This is not error - see [code_runner.nvim](https://github.com/CRAG666/code_runner.nvim)
Try last commit - now support snapshots!
Preconfigured json file for `code_runner.nvim` - in folder `lvim/config/code_runner/`
