### ISSUE TITLE
<C-z> is breaking standard terminal behavior

### ISSUE THREAD

**Issue by rolfst** [lvim-tech/lvim#41]
Hi when pressing `<C-z>` in lvim it opens a neozoom window. this however breaks default terminal behavior of killing the application. Should we change this to something like `<C-S-Z>`?

**Comment by lvim-tech** [comment]
`{ "<C-c>e", ":qa!<CR>" }`

**Comment by lvim-tech** [comment]
You can re-write all keybindings:
1. In `lua/configs/user/init.lua`:
```
local funcs = require("core.funcs")
local keymaps = require("configs.user.keymaps")

local configs = {}

configs["base_keymaps"] = false;

configs["user_keymaps"] = function()
    funcs.keymaps("n", { noremap = false, silent = true }, keymaps.normal)
    funcs.keymaps("x", { noremap = false, silent = true }, keymaps.visual)
end

return configs;
```
2. In `lua/configs/user/keymaps.lua`:
```
local keymaps = {}

keymaps["normal"] = {
--
}

keymaps["visual"] = {
-- 
}

return keymaps
```
Also you can re-write all plugin settings

**Comment by rolfst** [comment]
I know I can rewrite the keymaps. but don't you think we should leave the more common ones alone? Just a thought? with `<C-z>` there can be reasons to kill the application instead of quitting elegantly.
Also I think most of your other keybindings are good chosen ones so I really don't like to copy-paste all keys and adjust only 1 or 2 or is this the way for lvim? which in that case I can adjust to if that is the pattern to go to.

**Comment by lvim-tech** [comment]
Try last commit. NeoZoomToggle re-mapped to `<C-c>z`
