### ISSUE TITLE
ESC + j/k swaps lines

### ISSUE THREAD

**Issue by dlaukamp** [lvim-tech/lvim#42]
Hello,

first, I've have to say I've picked up using LunarVim again after some months now and I've to say it's amazing how much has improved, thanks a lot!

The issue I've noticed after upgrading to the most recent stable version is that when in insert mode, pressing ESC and either 'j' or 'k' afterwards, it swaps the current line with the one below/ above and stays in insert mode. In normal mode, if I hold ESC and then press 'j'/'k', the same thing happens, just that I stay in normal mode.
The effect is essentially identical to pressing 'dd' and 'p'/ 'P' afterwards.

How can I change this behavior so that I can move around normally?

```
lvim --version                                                                                                                                                                                              

NVIM v0.7.2
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1
```

**Comment by lvim-tech** [comment]
This is not [LunarVim](https://github.com/LunarVim/LunarVim)

**Comment by dlaukamp** [comment]
Arg, sorry!
