### ISSUE TITLE
module 'nui.utils.autocmd'

### ISSUE THREAD

**Issue by pizsd** [lvim-tech/lvim#44]
处理 /Users/zerduo/.config/nvim/init.lua 时发生错误:
E5113: Error while calling lua chunk: /Users/zerduo/.config/nvim/lua/configs/base/ui/select.lua:2: module 'nui.utils.autocmd' not found:
        no field package.preload['nui.utils.autocmd']
        no file './nui/utils/autocmd.lua'
        no file '/usr/local/share/luajit-2.1.0-beta3/nui/utils/autocmd.lua'
        no file '/usr/local/share/lua/5.1/nui/utils/autocmd.lua'
        no file '/usr/local/share/lua/5.1/nui/utils/autocmd/init.lua'
        no file './nui/utils/autocmd.so'
        no file '/usr/local/lib/lua/5.1/nui/utils/autocmd.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './nui.so'
        no file '/usr/local/lib/lua/5.1/nui.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /Users/zerduo/.config/nvim/lua/configs/base/ui/select.lua:2: in main chunk
        [C]: in function 'require'
        /Users/zerduo/.config/nvim/lua/core/funcs.lua:2: in main chunk
        [C]: in function 'require'
        /Users/zerduo/.config/nvim/lua/core/init.lua:6: in main chunk
        [C]: in function 'require'
        /Users/zerduo/.config/nvim/init.lua:9: in main chunk

**Comment by lvim-tech** [comment]
Neovim version, OS?
Update to the latest commit and try `:PackerSync`

**Comment by dhensen** [comment]
I am having this issue too. I already am using lvim for a month and half. But I messed up my ~/.config/nvim and the ~/.local/share/nvim so I decided to rm -rf those and start again by cloning. But then this error pops up. I worked around it by checking out tag `2.2.08`, then launch nvim, let it install.... Then checkout `production` branch do a PackerSync. Now for me it's fine again, but this stuff is not my cup tea. So I'll let you pro's handle this one ;)

**Comment by dhensen** [comment]
Oh btw:

```
nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

I'm running Arch™ BTW.

**Comment by lvim-tech** [comment]
@pizsd  @dhensen Thanks for the report!
Try the last commit. I think this problem is solved.
I would appreciate a reply.

**Comment by dhensen** [comment]
@lvim-tech  sure, a reply is the least I can do ;)

After git pulling production I end up on a0ddf059146b56029152e24f4a935ebb37dc766b. I straigh away open nvim and I get the errorr (this is on another machine I was on yesterday, I came from a september 14 commit 41698a9b5f1cb4d0d9b739b07263c99b564b446d).

![2022-10-12-160101_1920x1080_scrot](https://user-images.githubusercontent.com/2786295/195363884-95d61d71-6668-48b6-9abe-3b63894c7bb9.png)

**Comment by dhensen** [comment]
@lvim-tech after PackerSync and restart of nvim this error message no longer pops up :+1:

**Comment by lvim-tech** [comment]
@dhensen Thanks!
