### ISSUE TITLE
Error when editor cpp files, need your help!

### ISSUE THREAD

**Issue by whitemoon** [lvim-tech/lvim#47]
![图片](https://user-images.githubusercontent.com/11935167/198494120-c19da672-cfaa-4458-a122-78c7af9bf103.png)

when save file:
![图片](https://user-images.githubusercontent.com/11935167/198494576-e7a25e3f-497d-4da1-81bb-11dd51875150.png)
nvim version: v0.8.0 release
lvim version: production last

**Comment by lvim-tech** [comment]
@whitemoon, try last commit (updated)

**Comment by whitemoon** [comment]
Thank you very much. One more question, when Turn pages with 'G' or 'gg'， then nvim will segmentation fault.
![图片](https://user-images.githubusercontent.com/11935167/198511549-2dbbeeff-a225-4024-9d06-5a602ab84ec9.png)

**Comment by whitemoon** [comment]
ctrl+f or ctrl+b also can segmentation fault.

**Comment by lvim-tech** [comment]
Terminal?

**Comment by whitemoon** [comment]
yes, konsole, It is the same as using the Alacrity

**Comment by lvim-tech** [comment]
I tested it on a Alacrity - no problem.
Try to disable `declancm/cinnamon.nvim`
In file `lua/modiles/base/init.lua` just comment 404-410 lines
```
-- modules["declancm/cinnamon.nvim"] = {
--     commit = funcs.get_commit("cinnamon.nvim", plugins_snapshot),
--     event = {
--         "BufRead",
--     },
--     config = editor_config.cinnamon_nvim,
-- }
```
And run `PackerSync`

**Comment by whitemoon** [comment]
yeh, disable declancm/cinnamon.nvim is ok, not segmentation fault.

**Comment by lvim-tech** [comment]
I replaced `declancm/cinnamon.nvim` with `karb94/neoscroll.nvim`.
Please, try last commit to test it. Thanks in advance.

**Comment by whitemoon** [comment]
no problem, 'karb94/neoscroll.nvim' works very well, Thanks a lot!
