### ISSUE TITLE
standard vim behavior: go to linenumber no longer works

### ISSUE THREAD

**Issue by rolfst** [lvim-tech/lvim#48]
- delete rest of line no longer works
  when I do 'D' i open neotree dir
- go to linenumber no longer works
when I do `10G` i expect to go to line number 10 but instead I get the error message: `E481: No range allowed`

**Comment by lvim-tech** [comment]
I tested it. Works on nvim 0.8 and nightly. Lvim commit?

**Comment by rolfst** [comment]
latest commit does work but I found delete rest of line still doesn't

**Comment by lvim-tech** [comment]
<S-d> fixed
