### ISSUE TITLE
snippetRun works against surround or lspsignaturehelp

### ISSUE THREAD

**Issue by rolfst** [lvim-tech/lvim#49]
Hi,
When wanting to use `gs` (normal-mode) for snippetRun this is blocked by the same binding for lspSignatureHelp
when using `gS` (visual-mode) for snippetRun it clashes with surround. (after pressing another character key this will be the surrounding character).

maybe use `sR` for both modes to activate snippetRun?

**Comment by lvim-tech** [comment]
Fixed - `ts` for SnipRun
