### ISSUE TITLE
Custom config

### ISSUE THREAD

**Issue by hunderaweke** [lvim-tech/lvim#50]
I have an issue with custom configuration I didn't understand how to do it expalanation please...

**Comment by lvim-tech** [comment]
@HunderaAwoke What do you want to configure?

**Comment by hunderaweke** [comment]
Some plugins like rnvimr, symbolsoutline, and colorschemes and their keymapping and vim multi and I didn't get how to configure them.
And I wanted to use toggle term custom config.

**Comment by lvim-tech** [comment]
All plugins are defined in `lua/modules/base/init.lua`.

In `lua/modules/user/init.lua`:

```
-- Disable plugin
modules["simrat39/symbols-outline.nvim"] = false

-- Rewrite config of the plugin
modules["simrat39/symbols-outline.nvim"] = {
-- your config
}

-- Add new plugin
modules["your/plugin"] = {
-- your config
}
```

**Comment by lvim-tech** [comment]
@HunderaAwoke Did you succeed?
