### ISSUE TITLE
Recommend: Markdown-preview plugins changed!

### ISSUE THREAD

**Issue by whitemoon** [lvim-tech/lvim#51]
I would suggest replacing markdown-preview plugins with "iamcco/markdown-preview.nvim",because it is more powerful, it supports a lot of Markdown plugins.

**Comment by lvim-tech** [comment]
What about this:
https://github.com/toppair/peek.nvim

**Comment by whitemoon** [comment]
If this supports previews like mermaid, I can, because I sometimes draw some flow-process diagram

**Comment by lvim-tech** [comment]
Replaced
