### ISSUE TITLE
<C-space> does not execute NeoZoom<CR> but opens the leader menu bar

### ISSUE THREAD

**Issue by dhensen** [lvim-tech/lvim#52]
![image](https://user-images.githubusercontent.com/2786295/199346195-75c9fe83-deac-4e18-8480-688317b8caa6.png)
When I do <C-space> (this is meant to be CTRL+space right?) NeoZoom does not happen, but instead I get the bar at the bottom.

I'm on f82215d3543b01d488660945c1a72e90f6a1d904
I dont have any customizations except for some null_ls stuff (configured yapf,mypy,pyright)

**Comment by lvim-tech** [comment]
`<space>` - WhichKey
`<space><space>` - CtrlSpace
`C-space` - NeoZoom

**Comment by dhensen** [comment]
So then when I press C-space I'm getting WhichKey. This is on WSL2 inside of tmux, I'm having loads of WSL related issues though, so getting a bit paranoia about what is causing this.

**Comment by lvim-tech** [comment]
On linux and mac (+tmux) it works. 
I'm moved all keymaps for plugins into plugin's configuration.
Rewrite config for NeoZoom to test it.
timeoutlen=?

**Comment by dhensen** [comment]
I just tested on a Linux box, no problem there. It's a Windows/WSL(2) issue 100%.
timeoutlen=500

I've set it to 50, but no difference. I'm fine with giving up, this is a corporate laptop, I dont have much control over it. I'll work around this.

**Comment by dhensen** [comment]
Found it: alacritty on windows is the issue.
When using Windows Terminal it just werks.
Thanks for helping me out
