### ISSUE TITLE
I got an Error while open it

### ISSUE THREAD

**Issue by YSW0630** [lvim-tech/lvim#53]
Error detected while processing /home/justin/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/justin/.config/nvim/lua/core/funcs.lua:2: module 'lvim-ui-config.select' not found:
        no field package.preload['lvim-ui-config.select']
        no file './lvim-ui-config/select.lua'
        no file '/usr/share/luajit-2.1.0-beta3/lvim-ui-config/select.lua'
        no file '/usr/local/share/lua/5.1/lvim-ui-config/select.lua'
        no file '/usr/local/share/lua/5.1/lvim-ui-config/select/init.lua'
        no file '/usr/share/lua/5.1/lvim-ui-config/select.lua'
        no file '/usr/share/lua/5.1/lvim-ui-config/select/init.lua'
        no file './lvim-ui-config/select.so'
        no file '/usr/local/lib/lua/5.1/lvim-ui-config/select.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/lvim-ui-config/select.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './lvim-ui-config.so'
        no file '/usr/local/lib/lua/5.1/lvim-ui-config.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/lvim-ui-config.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/justin/.config/nvim/lua/core/funcs.lua:2: in main chunk
        [C]: in function 'require'
        /home/justin/.config/nvim/lua/core/init.lua:6: in main chunk
        [C]: in function 'require'
        /home/justin/.config/nvim/init.lua:9: in main chunk

**Comment by lvim-tech** [comment]
Fixed, try `PackerSync`.
If no result - try the latest commit.

**Comment by YSW0630** [comment]
Thanks reply! but I don't have `PackerSync` option

**Comment by lvim-tech** [comment]
Delete `~/.local/share/nvim/site/lua/packer_compiled.lua`, start nvim and then run `:PackerSync`

**Comment by YSW0630** [comment]
ok, I'll check it!
