### ISSUE TITLE
Keybinding `gf` overrides default vim functionality

### ISSUE THREAD

**Issue by rolfst** [lvim-tech/lvim#54]
Hi I found pressing `gf` is assigned as a shortcut to format document. however this is overriding a default vimbinding that when your cursor is on a file location string it will open a buffer with that file.
this is particulary useful to navigate when in the terminal an exception is thrown that shows the location of the file.

**Comment by lvim-tech** [comment]
Just use `gF` or `<C-w><C-f>`. They are similar.
Or comment map `gf` in `lua/modules/base/configs/languages/init.lua`.
Or move mason settings from `base` to `user` folder.
