### ISSUE TITLE
commit that introduced lvim-ui-config breaks lvim

### ISSUE THREAD

**Issue by dhensen** [lvim-tech/lvim#55]
In commit 5d04e2cd4b34748ea14e8c8e0f8bb9f96810c582 lvim-ui-config was introduced. When doing git pull just 10 minutes ago, after starting up nvim my setup was broken. But because lots of stuff now depends on lvim-ui-config, packer is not even being loaded. So I can't fix it this time issuing `PackerInstall` like I normally would. How to proceed?

I think it would be nice to have some preloading/preinstalling of packages before running code that depends on it, but not sure how hard that would be, given that dependencies are defined in the code itself.

**Comment by lvim-tech** [comment]
Delete `~/.local/share/nvim/site/lua/packer_compiled.lua`, start nvim and then run `:PackerSync`
If you want to stay at this commit, update commit for `lvim-ui-config` in `.snapshots/default` to `5677f62`.

**Comment by dhensen** [comment]
This does not  solve it for me. After deleting packer_compiled.lua the setup is still dependenant on lvim-ui-config.select.
So I now have no access to any Packer* commands.

```
Error detected while processing /home/dino/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/dino/.config/nvim/lua/core/funcs.lua:2: module 'lvim-ui-config.select' not found:
        no field package.preload['lvim-ui-config.select']
        no file './lvim-ui-config/select.lua'
        no file '/usr/share/luajit-2.1.0-beta3/lvim-ui-config/select.lua'
        no file '/usr/local/share/lua/5.1/lvim-ui-config/select.lua'
        no file '/usr/local/share/lua/5.1/lvim-ui-config/select/init.lua'
        no file '/usr/share/lua/5.1/lvim-ui-config/select.lua'
        no file '/usr/share/lua/5.1/lvim-ui-config/select/init.lua'
        no file './lvim-ui-config/select.so'
        no file '/usr/local/lib/lua/5.1/lvim-ui-config/select.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/lvim-ui-config/select.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './lvim-ui-config.so'
        no file '/usr/local/lib/lua/5.1/lvim-ui-config.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/lvim-ui-config.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/dino/.config/nvim/lua/core/funcs.lua:2: in main chunk
        [C]: in function 'require'
        /home/dino/.config/nvim/lua/core/init.lua:6: in main chunk
        [C]: in function 'require'
        /home/dino/.config/nvim/init.lua:9: in main chunk
Press ENTER or type command to continue
```

**Comment by dhensen** [comment]
I worked around this issue by doing:

```
cd ~/.config/nvim/lua
git clone https://github.com/lvim-tech/lvim-ui-config.git lvim-ui-config-repo
ln -s lvim-ui-config-repo/lua/lvim-ui-config .
```

After this my nvim can start and load lvim setup, I can then `PackerSync` and cleanup what I did above.

> for future reference, I checked out the lvim-ui-config at commit 5677f620e12656bb5c2e4b59514a18c1a113af53

**Comment by dhensen** [comment]
@rolfst mentioned that lvim-config-ui is not present as a toplevel module in modules/base/init.lua
