### ISSUE TITLE
Question about core-dependencies in LVIM

### ISSUE THREAD

**Issue by rolfst** [lvim-tech/lvim#56]
Hi I noticed that in this commit and file: https://github.com/lvim-tech/lvim/commit/5d04e2cd4b34748ea14e8c8e0f8bb9f96810c582#diff-dcd859ee146ad8cc0db26e5e9bd6f8113b8044f5b49382fbbb9c08519add6f4b 
2 new requires were introduced but if you start with a clean install of Lvim, can this work? Packer hasn't installed them yet has it? so won't it break the rest of the loading of lvim?

and if this doesn't make it fail what am I missing?

**Comment by lvim-tech** [comment]
Fixed. Thanks!
