### ISSUE TITLE
lvim notification hell ;)

### ISSUE THREAD

**Issue by rolfst** [lvim-tech/lvim#57]
Hi just wondering if it is possible to stop displaying notifications somehow.
sometimes I perform an action like removing a folder in my neotree and then I immediately want to swap to my test status outline on the opposite of the screen. but I can't see where my cursor lands because of the popup indicating my action has succeeded.

Can we somehow make it possible to not show these popups?

**Comment by lvim-tech** [comment]
Only for neo-tree?

**Comment by rolfst** [comment]
no in general? Sometimes it's not just 1 popup but a lot of them arranged below each other.

**Comment by lvim-tech** [comment]
Solution 1: disable `folke/noice.nvim` and set `cmdheight=1`
Solution 2: `noice.setup({messages = {enabled = false}})` - (not recomended - this disable api messages)
Solution 3: add custom `routes` for `folke/noice.nvim`

**Comment by lvim-tech** [comment]
@rolfst, If you find a solution with a global setting, please send a PR, I'll merge it.

**Comment by rolfst** [comment]
I think I'll look for a solution with a global setting. 
just disabling noice will not be a good solution since it will also hamper the popups for installing other plugins or Mason resources

**Comment by lvim-tech** [comment]
Mason use vim.notify and not will be affected.

**Comment by lvim-tech** [comment]
Reopen this issue when you have any solution.
