### ISSUE TITLE
<A-1> , <A-2> keys dont cause any dap action 

### ISSUE THREAD

**Issue by gminorcoles** [lvim-tech/lvim#59]
I just installed LVIM and I am trying to test debugging on a file in a project which is giving me some problems in AstroNvim. I cant really make any sense of LVIM. I see keybindings for dap, but when I hit option-1 or 2 on my Mac keyboard, there is no perceptible activity. Also if I simply try to do :!python3 %, it pauses for a while but I see no output. 

There are no docs which I guess is by design? LVIM seems cool but I cant really get started.

**Comment by lvim-tech** [comment]
`<A-1>` is `Alt + 1`
Try to change keymaps in `lua/modules/base/configs/languages/init.lua` (lines 546-577)
