### ISSUE TITLE
module 'core.funcs.search' not found

### ISSUE THREAD

**Issue by yofriadi** [lvim-tech/lvim#6]
Hi, could you please take a look where this module come from, thankyou

```
{
    '*',
    ':<C-u>lua require("core.funcs.search").visual_selection("/")<CR>/<C-r>=@/<CR><CR>'
}, -- Visual search /
{
    '#',
    ':<C-u>lua require("core.funcs.search").visual_selection("?")<CR>?<C-r>=@/<CR><CR>'
}, -- Visual search ?
```

**Comment by lvim-tech** [comment]
Pull update from ~/config/nvim
git pull origin main
Then:
:PackerSync
Restart

@yofriadi Please tell if it works

**Comment by yofriadi** [comment]
well it's removed apparently, maybe you want to update the readme too.
