### ISSUE TITLE
treesitter is using all of the CPU/memory resources at first run.

### ISSUE THREAD

**Issue by ArthurTheReal** [lvim-tech/lvim#61]
I installed the configurations and ran the nvim and it installed the plugins completly, 
but now, when I run nvim, there is a notification say that treesitter is doing something and then my CPU/memory usage will pop up to maximum and OS will crash.

and I'm using it in linux

is there a problem with treesitter or something?
I appreciate it if you help me :)

**Comment by lvim-tech** [comment]
Mayby treesitter install parsers
In `lua/modules/base/configs/languages/init.lua` replace 

```lua
nvim_treesitter_configs.setup({
        ensure_installed = "all",
        ...
```
with 
```lua
nvim_treesitter_configs.setup({
        ensure_installed = {"html", "javascript", "parser_you_want"},
```

**Comment by ArthurTheReal** [comment]
It worked!, Thanks!
