### ISSUE TITLE
config.json theme are not used upon start

### ISSUE THREAD

**Issue by davidqge** [lvim-tech/lvim#63]
I used LvimTheme to set the theme. 

It saved the choice to config.json automatically:
{"keyshelper": true, "floatheight": 0.4, "virtualdiagnostic": false, "autoformat": true, "theme": "lvim-light", "inlayhint": true, "keyshelperdelay": 200}

But when restart, it still show dark theme, not light in config.json

**Comment by lvim-tech** [comment]
Strange.
Try changing some of the other settings to see if they load.
