### ISSUE TITLE
lvim-light theme are not restored properly upon start 

### ISSUE THREAD

**Issue by davidqge** [lvim-tech/lvim#64]
I used LvimTheme to change the theme to lvim-light.
`lvim-light` is saved to  `.configs/lvim/config.json`

after restart, `G.LVIM_SETTINGS.theme`  is `lvim-light`

But In `lua/modules/base/configs/ui/init.lua`
```
    vim.cmd("colorscheme " .. _G.LVIM_SETTINGS.theme)
```
didn't change the theme to light.

Work around:
1. after fully start, `colorscheme lvim-light` do change the theme to light.
2. if I set
```
      vim.opt.background="light"
```
before `lua/modules/base/configs/ui/init.lua`, it also works.

**Comment by lvim-tech** [comment]
Try the latest commit

**Comment by davidqge** [comment]
Yes, working now.

Thank you!
