### ISSUE TITLE
Feat - Add support for a better session/project manager

### ISSUE THREAD

**Issue by Ajaymamtora** [lvim-tech/lvim#66]
Would it be possible to add support for something like: https://github.com/coffebar/neovim-project
or https://github.com/stevearc/resession.nvim ?

Whenever I try to set them up and load a session, LSP breaks. Running LspRestart doesnt fix it

**Comment by lvim-tech** [comment]
For sessions, Lvim utilizes https://github.com/vim-ctrlspace/vim-ctrlspace. This is the most powerful plugin for project organization - it adds workspaces, bookmarks, tabs, fuzzy search, and many other features.
