### ISSUE TITLE
slow except I open a lua file first

### ISSUE THREAD

**Issue by maximussong** [lvim-tech/lvim#7]
This is a really nice work. I enjoy it very much so far, but I find a weird issue when running lvim. It loads the dashboard and saves buffers very slow on my Ubuntu 20.04, except I first open a lua file in the .config/nvim subdirectory. I tried many different terminal apps, the results remain the same. Could you please give me some hints on how did this happen, so I can try to fix it?
Many thanks!!!!

**Comment by lvim-tech** [comment]
Run LVim wit startuptime options
`vim --startuptime timecost.txt`
for more details

**Comment by maximussong** [comment]
Thanks for your reply. I removed a few plugins ,and it runs fast on my ubuntu os now.
Cheers!
