### ISSUE TITLE
fresh install on macos with missing plugin

### ISSUE THREAD

**Issue by maximussong** [lvim-tech/lvim#8]
I made a fresh install on macos. It shows successful on installing all the plugins. However, when I run nvim, it show "No icon plugin found. Please install 'kyazdani42/nvim-web-devicons'".
I check the status and it shows that plugin was installed, and the folder is there too.
Could you please give me some hint on how to fix it?

Many thanks!!!

**Comment by lvim-tech** [comment]
Try with last commit.
